In [31]:
from sklearn.datasets import load_iris
iris= load_iris()

In [32]:
X=iris.data
y=iris.target

In [33]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [34]:
import pandas as pd
pd.DataFrame(X,columns=iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [35]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
knn.predict([[3,5,4,2]])

array([1])

In [38]:
simple_train=['call you tonight', 'Call me a cab','please call me... PLEASE!!']

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
#vect=CountVectorizer()
vect = CountVectorizer(ngram_range=(3, 3))
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(3, 3), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [40]:
vect.get_feature_names()

['call me cab', 'call me please', 'call you tonight', 'please call me']

In [41]:
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [42]:
simple_train_dtm.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 1]], dtype=int64)

In [43]:
pd.DataFrame(simple_train_dtm.toarray(),columns=vect.get_feature_names())

call me cab  call me please  call you tonight  please call me
0            0               0                 1               0
1            1               0                 0               0
2            0               1                 0               1

In [44]:
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [45]:
print(simple_train_dtm)

  (0, 2)	1
  (1, 0)	1
  (2, 1)	1
  (2, 3)	1


In [46]:
simple_text=["please don't call me"]

In [47]:
simple_text_dtm = vect.transform(simple_text)
simple_text_dtm.toarray()

array([[0, 0, 0, 0]], dtype=int64)

In [48]:
pd.DataFrame(simple_text_dtm.toarray(),columns=vect.get_feature_names())

call me cab  call me please  call you tonight  please call me
0            0               0                 0               0

In [49]:
url = 'https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'
sms = pd.read_table(url, header=None, names=['label', 'message'])

In [50]:
sms.shape

(5572, 2)

In [51]:
sms.head()
#type(sms)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [52]:
# examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [53]:
# convert label to a numerical variable
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [54]:
# check that the conversion worked
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [55]:
X = sms.message
y = sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [56]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)


C:\DevTools\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [57]:
vect = CountVectorizer()

In [58]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [59]:
# equivalently: combine fit and transform into a single step
X_train_dtm = vect.fit_transform(X_train)

In [60]:
# examine the document-term matrix
X_train_dtm

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [61]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [63]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [64]:
%time nb.fit(X_train_dtm, y_train)

Wall time: 1.08 s


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [65]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [66]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9885139985642498

In [67]:
print(y_pred_class)

[0 0 0 ... 0 1 0]
